[build]
  command = "npm run build"
  publish = "dist"

# Handle SPA routing (React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  # Set NODE_VERSION for the build - Updated to match local environment
  NODE_VERSION = "24" 